CREATE TYPE "public"."classificacao_imc" AS ENUM('Abaixo do peso', 'Peso normal', 'Sobrepeso', 'Obesidade Grau I', 'Obesidade Grau II', 'Obesidade Grau III');--> statement-breakpoint
CREATE TYPE "public"."sexo" AS ENUM('masculino', 'feminino');--> statement-breakpoint
CREATE TABLE "assessments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"student_id" uuid NOT NULL,
	"data" date NOT NULL,
	"altura" double precision,
	"peso" double precision,
	"imc" double precision,
	"classificacao_imc" "classificacao_imc",
	"circ_ombro" double precision,
	"circ_torax" double precision,
	"circ_cintura" double precision,
	"circ_abdominal" double precision,
	"circ_quadril" double precision,
	"circ_braco_normal_esq" double precision,
	"circ_braco_normal_dir" double precision,
	"circ_braco_contraido_esq" double precision,
	"circ_braco_contraido_dir" double precision,
	"circ_antebraco_esq" double precision,
	"circ_antebraco_dir" double precision,
	"circ_coxa_esq" double precision,
	"circ_coxa_dir" double precision,
	"circ_panturrilha_esq" double precision,
	"circ_panturrilha_dir" double precision,
	"dobra_triceps" double precision,
	"dobra_peito" double precision,
	"dobra_axilar_media" double precision,
	"dobra_subescapular" double precision,
	"dobra_abdominal" double precision,
	"dobra_supra_iliaca" double precision,
	"dobra_coxa" double precision,
	"massa_magra" double precision,
	"massa_gorda" double precision,
	"percentual_gordura" double precision,
	"foto_anterior" text,
	"foto_posterior" text,
	"foto_lado_esquerdo" text,
	"foto_lado_direito" text,
	"observacoes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "students" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"nome" varchar(150) NOT NULL,
	"idade" integer NOT NULL,
	"sexo" "sexo" NOT NULL,
	"contato" varchar(30) NOT NULL,
	"email" varchar(255) NOT NULL,
	"ja_treinou_antes" boolean DEFAULT false NOT NULL,
	"tempo_de_treino" text,
	"tempo_sem_atividade_fisica" text,
	"objetivo" text,
	"frequencia_semanal" integer,
	"tempo_treino_por_dia" text,
	"tem_doenca_ou_problema_saude" boolean DEFAULT false NOT NULL,
	"doenca_ou_problema_saude_detalhe" text,
	"tem_limitacao_movimento" boolean DEFAULT false NOT NULL,
	"limitacao_movimento_detalhe" text,
	"tem_dor_em_movimento" boolean DEFAULT false NOT NULL,
	"dor_em_movimento_detalhe" text,
	"fez_cirurgias" boolean DEFAULT false NOT NULL,
	"cirurgias_detalhe" text,
	"usa_medicamento_controlado" boolean DEFAULT false NOT NULL,
	"medicamento_controlado_detalhe" text,
	"esta_fazendo_dieta" boolean DEFAULT false NOT NULL,
	"consome_alcool" boolean DEFAULT false NOT NULL,
	"fuma" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "students_email_unique" UNIQUE("email")
);
--> statement-breakpoint
ALTER TABLE "assessments" ADD CONSTRAINT "assessments_student_id_students_id_fk" FOREIGN KEY ("student_id") REFERENCES "public"."students"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "assessments_student_data_idx" ON "assessments" USING btree ("student_id","data");